id: P005590
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W8LS20054
  title: བཀའ་རྫོགས་པ་ཆེན་པོའི་ལོ་རྒྱུས་ཉེར་མཁོ།
  author: ''
  volumes:
    0aaab66f67b34b39be212742ed839f60:
      image_group_id: I8LS20056
      title: ''
      volume_number: 1
      total_pages: 66
      base_file: v001.txt
