id: I65D9B65D
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T09:02:38+00:00'
last_modified: '2022-06-08T05:08:14.111573+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS20054
  title: བཀའ་རྫོགས་པ་ཆེན་པོའི་ལོ་རྒྱུས་ཉེར་མཁོ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    0C6D:
      image_group_id: I8LS20056
      title: ''
      total_pages: 66
      order: 1
      base_file: 0C6D.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
